apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: ""
    openshift.io/requester: opentlc-mgr
    openshift.io/sa.scc.mcs: s0:c26,c20
    openshift.io/sa.scc.supplemental-groups: 1000690000/10000
    openshift.io/sa.scc.uid-range: 1000690000/10000
    operator.tekton.dev/prune.hash: e12cf88878007ab90299fa28c92d42daf72a1dda6ff604ea40c1f1da0f1f5e1d
  labels:
    kiali.io/member-of: istio-system
    kubernetes.io/metadata.name: istio-system
    maistra.io/ignore-namespace: ignore
    maistra.io/member-of: istio-system
    openshift-pipelines.tekton.dev/namespace-reconcile-version: 1.7.0
  name: istio-system
spec:
  finalizers:
  - kubernetes
