apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-system
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: Role
  name: istio-system
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops