apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bookinfo
  namespace: bookinfo
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: Role
  name: bookinfo
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops