apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-app
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: bookinfo
    server: 'https://kubernetes.default.svc'
  source:
    path: 0-bookinfo/app/base
    repoURL: 'https://github.com/mgohashi/workshop-rht-servicemesh.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true