apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-gitops-ns
  namespace: openshift-gitops
spec:
  destination:
    name: ''
    namespace: openshift-gitops
    server: 'https://kubernetes.default.svc'
  source:
    path: pre-req
    repoURL: 'https://github.com/mgohashi/workshop-rht.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true