apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: test-app
  namespace: test-app
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: Role
  name: test-app
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops